---
- include_tasks: mount.yml
- name: Create Frigate Directory Structure
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: docker
  loop:
    - /opt/frigate
    - /opt/frigate/config
    - /opt/frigate/storage

- name: Deploy Frigate Configuration
  template:
    src: config.yml.j2
    dest: /opt/frigate/config/config.yml
    mode: '0644'
  notify: Restart Frigate

- name: Deploy Frigate Container
  docker_container:
    name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    state: started
    restart_policy: unless-stopped
    privileged: yes
    shm_size: "128m"
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    networks:
      - name: vault_net
      - name: tribe_net
